package com.agroconnect.model;

/**
 * Represents a Farmer in AgroConnect
 * Demonstrates inheritance (FarmerUser extends User)
 */
public class FarmerUser extends User {

    private String phone;
    private String location;

    // Constructor used when loading farmer from database (id known)
    public FarmerUser(int id, String name, String email, String password, String phone, String location) {
        super(id, name, email, password);
        this.phone = phone;
        this.location = location;
    }

    // Constructor used when registering a new farmer (id auto-generated by DB)
    public FarmerUser(String name, String email, String password, String phone, String location) {
        this(0, name, email, password, phone, location);
    }

    @Override
    public String getRole() {
        return "FARMER";
    }

    // Getters and setters
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
}